// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEJ4R8yAv1rdr-pvPO3PY8jiMiI8_g9w',
    appId: '1:661948777385:web:04168c8b6825caaeff3ab8',
    messagingSenderId: '661948777385',
    projectId: 'constituency-b105f',
    authDomain: 'constituency-b105f.firebaseapp.com',
    storageBucket: 'constituency-b105f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQ3hy79khiK_CLD6TsrfEvHBBYQjyyAw',
    appId: '1:661948777385:android:50e2c64ff283a331ff3ab8',
    messagingSenderId: '661948777385',
    projectId: 'constituency-b105f',
    storageBucket: 'constituency-b105f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFyGhIOBc-D0QHiX8DYgcJqtqr55pJrk',
    appId: '1:661948777385:ios:b24651eb6a3463cbff3ab8',
    messagingSenderId: '661948777385',
    projectId: 'constituency-b105f',
    storageBucket: 'constituency-b105f.appspot.com',
    iosClientId: '661948777385-95c26ob5klii1e8uq9j8paf5kd49c0ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFyGhIOBc-D0QHiX8DYgcJqtqr55pJrk',
    appId: '1:661948777385:ios:b24651eb6a3463cbff3ab8',
    messagingSenderId: '661948777385',
    projectId: 'constituency-b105f',
    storageBucket: 'constituency-b105f.appspot.com',
    iosClientId: '661948777385-95c26ob5klii1e8uq9j8paf5kd49c0ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPortal',
  );
}
